### ISSUE TITLE
Issue-update doc

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/bestside-exchange#150]
Automated Review Comments
Issues in README.md:
  - (3, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (36, 'Hardcoded string found')
  - (37, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')
  - (39, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (42, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (48, 'Hardcoded string found')
  - (49, 'Line exceeds 80 characters')
  - (50, 'Line exceeds 80 characters')
  - (50, 'Hardcoded string found')
  - (52, 'Line exceeds 80 characters')

**Comment by lind0118** [comment]
I got it.
