### ISSUE TITLE
Issue-design frontend table

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/bestside-exchange#18]
Automated Review Comments
Issues in frontend/craco.config.js:
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in frontend/package.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
Issues in frontend/src/App.js:
  - (3, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
  - (46, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (67, 'Line exceeds 80 characters')
  - (69, 'Line exceeds 80 characters')
  - (79, 'Line exceeds 80 characters')
  - (80, 'Line exceeds 80 characters')
  - (80, 'Hardcoded string found')
  - (90, 'Line exceeds 80 characters')
  - (97, 'Line exceeds 80 characters')
  - (97, 'Hardcoded string found')
  - (100, 'Line exceeds 80 characters')
  - (100, 'Hardcoded string found')
  - (136, 'Line exceeds 80 characters')
  - (148, 'Line exceeds 80 characters')
  - (163, 'Line exceeds 80 characters')
  - (164, 'Line exceeds 80 characters')
  - (169, 'Hardcoded string found')
  - (170, 'Line exceeds 80 characters')
  - (175, 'Hardcoded string found')
  - (176, 'Line exceeds 80 characters')
  - (181, 'Hardcoded string found')
  - (182, 'Line exceeds 80 characters')
  - (187, 'Hardcoded string found')
  - (188, 'Line exceeds 80 characters')
  - (192, 'Hardcoded string found')
  - (201, 'Line exceeds 80 characters')
  - (207, 'Line exceeds 80 characters')
  - (208, 'Line exceeds 80 characters')
  - (215, 'Line exceeds 80 characters')
  - (217, 'Line exceeds 80 characters')
  - (218, 'Line exceeds 80 characters')
  - (220, 'Line exceeds 80 characters')
  - (221, 'Line exceeds 80 characters')
Issues in frontend/src/index.css:
  - (10, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
Issues in frontend/tailwind.config.js:
  - (5, 'Hardcoded string found')
Issues in frontend/yarn.lock:
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (30, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (33, 'Hardcoded string found')
  - (41, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (50, 'Line exceeds 80 characters')
  - (57, 'Line exceeds 80 characters')
  - (58, 'Line exceeds 80 characters')
  - (67, 'Line exceeds 80 characters')
  - (69, 'Line exceeds 80 characters')
  - (70, 'Line exceeds 80 characters')
  - (74, 'Line exceeds 80 characters')
  - (75, 'Line exceeds 80 characters')
  - (79, 'Line exceeds 80 characters')
  - (81, 'Line exceeds 80 characters')
  - (82, 'Line exceeds 80 characters')
  - (86, 'Line exceeds 80 characters')
  - (87, 'Line exceeds 80 characters')
  - (89, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (92, 'Hardcoded string found')
  - (133, 'Line exceeds 80 characters')
  - (140, 'Line exceeds 80 characters')
  - (141, 'Line exceeds 80 characters')
  - (145, 'Line exceeds 80 characters')
  - (147, 'Line exceeds 80 characters')
  - (148, 'Line exceeds 80 characters')
  - (152, 'Line exceeds 80 characters')
  - (153, 'Line exceeds 80 characters')
  - (157, 'Line exceeds 80 characters')
  - (162, 'Line exceeds 80 characters')
  - (164, 'Line exceeds 80 characters')
  - (165, 'Line exceeds 80 characters')
  - (169, 'Line exceeds 80 characters')
  - (176, 'Line exceeds 80 characters')
  - (177, 'Line exceeds 80 characters')
  - (181, 'Line exceeds 80 characters')
  - (183, 'Line exceeds 80 characters')
  - (188, 'Line exceeds 80 characters')
  - (189, 'Line exceeds 80 characters')
  - (195, 'Line exceeds 80 characters')
  - (202, 'Line exceeds 80 characters')
  - (203, 'Line exceeds 80 characters')
  - (207, 'Line exceeds 80 characters')
  - (208, 'Line exceeds 80 characters')
  - (212, 'Line exceeds 80 characters')
  - (214, 'Line exceeds 80 characters')
  - (215, 'Line exceeds 80 characters')
  - (219, 'Line exceeds 80 characters')
  - (220, 'Line exceeds 80 characters')
  - (224, 'Line exceeds 80 characters')
  - (226, 'Line exceeds 80 characters')
  - (231, 'Line exceeds 80 characters')
  - (238, 'Line exceeds 80 characters')
  - (240, 'Line exceeds 80 characters')
  - (241, 'Line exceeds 80 characters')
  - (246, 'Line exceeds 80 characters')
  - (247, 'Line exceeds 80 characters')
  - (249, 'Line exceeds 80 characters')
  - (250, 'Line exceeds 80 characters')
  - (255, 'Line exceeds 80 characters')
  - (256, 'Line exceeds 80 characters')
  - (258, 'Line exceeds 80 characters')
  - (259, 'Line exceeds 80 characters')
  - (263, 'Line exceeds 80 characters')
  - (264, 'Line exceeds 80 characters')
  - (268, 'Line exceeds 80 characters')
  - (275, 'Line exceeds 80 characters')
  - (276, 'Line exceeds 80 characters')
  - (278, 'Hardcoded string found')
  - (287, 'Line exceeds 80 characters')
  - (288, 'Line exceeds 80 characters')
  - (290, 'Hardcoded string found')
  - (298, 'Line exceeds 80 characters')
  - (299, 'Line exceeds 80 characters')
  - (301, 'Hardcoded string found')
  - (306, 'Line exceeds 80 characters')
  - (307, 'Line exceeds 80 characters')
  - (309, 'Hardcoded string found')
  - (317, 'Line exceeds 80 characters')
  - (318, 'Line exceeds 80 characters')
  - (320, 'Hardcoded string found')
  - (327, 'Line exceeds 80 characters')
  - (328, 'Line exceeds 80 characters')
  - (330, 'Hardcoded string found')
  - (336, 'Line exceeds 80 characters')
  - (337, 'Line exceeds 80 characters')
  - (339, 'Hardcoded string found')
  - (345, 'Line exceeds 80 characters')
  - (346, 'Line exceeds 80 characters')
  - (348, 'Hardcoded string found')
  - (354, 'Line exceeds 80 characters')
  - (355, 'Line exceeds 80 characters')
  - (357, 'Hardcoded string found')
  - (364, 'Line exceeds 80 characters')
  - (365, 'Line exceeds 80 characters')
  - (367, 'Hardcoded string found')
  - (373, 'Line exceeds 80 characters')
  - (374, 'Line exceeds 80 characters')
  - (376, 'Hardcoded string found')
  - (385, 'Line exceeds 80 characters')
  - (386, 'Line exceeds 80 characters')
  - (388, 'Hardcoded string found')
  - (396, 'Line exceeds 80 characters')
  - (398, 'Line exceeds 80 characters')
  - (399, 'Line exceeds 80 characters')
  - (401, 'Hardcoded string found')
  - (407, 'Line exceeds 80 characters')
  - (408, 'Line exceeds 80 characters')
  - (410, 'Hardcoded string found')
  - (417, 'Line exceeds 80 characters')
  - (418, 'Line exceeds 80 characters')
  - (420, 'Hardcoded string found')
  - (427, 'Line exceeds 80 characters')
  - (428, 'Line exceeds 80 characters')
  - (430, 'Hardcoded string found')
  - (435, 'Line exceeds 80 characters')
  - (436, 'Line exceeds 80 characters')
  - (438, 'Hardcoded string found')
  - (449, 'Line exceeds 80 characters')
  - (450, 'Line exceeds 80 characters')
  - (452, 'Hardcoded string found')
  - (457, 'Line exceeds 80 characters')
  - (458, 'Line exceeds 80 characters')
  - (460, 'Hardcoded string found')
  - (466, 'Line exceeds 80 characters')
  - (467, 'Line exceeds 80 characters')
  - (469, 'Hardcoded string found')
  - (476, 'Line exceeds 80 characters')
  - (477, 'Line exceeds 80 characters')
  - (479, 'Hardcoded string found')
  - (489, 'Line exceeds 80 characters')
  - (490, 'Line exceeds 80 characters')
  - (492, 'Hardcoded string found')
  - (500, 'Line exceeds 80 characters')
  - (501, 'Line exceeds 80 characters')
  - (503, 'Hardcoded string found')
  - (509, 'Line exceeds 80 characters')
  - (510, 'Line exceeds 80 characters')
  - (512, 'Hardcoded string found')
  - (518, 'Line exceeds 80 characters')
  - (519, 'Line exceeds 80 characters')
  - (521, 'Hardcoded string found')
  - (529, 'Line exceeds 80 characters')
  - (530, 'Line exceeds 80 characters')
  - (532, 'Hardcoded string found')
  - (541, 'Line exceeds 80 characters')
  - (542, 'Line exceeds 80 characters')
  - (544, 'Hardcoded string found')
  - (551, 'Line exceeds 80 characters')
  - (552, 'Line exceeds 80 characters')
  - (554, 'Hardcoded string found')
  - (559, 'Line exceeds 80 characters')
  - (560, 'Line exceeds 80 characters')
  - (562, 'Hardcoded string found')
  - (570, 'Line exceeds 80 characters')
  - (571, 'Line exceeds 80 characters')
  - (573, 'Hardcoded string found')
  - (581, 'Line exceeds 80 characters')
  - (582, 'Line exceeds 80 characters')
  - (584, 'Hardcoded string found')
  - (592, 'Line exceeds 80 characters')
  - (593, 'Line exceeds 80 characters')
  - (595, 'Hardcoded string found')
  - (599, 'Line exceeds 80 characters')
  - (601, 'Line exceeds 80 characters')
  - (602, 'Line exceeds 80 characters')
  - (604, 'Hardcoded string found')
  - (610, 'Line exceeds 80 characters')
  - (611, 'Line exceeds 80 characters')
  - (619, 'Line exceeds 80 characters')
  - (621, 'Line exceeds 80 characters')
  - (622, 'Line exceeds 80 characters')
  - (627, 'Line exceeds 80 characters')
  - (628, 'Line exceeds 80 characters')
  - (630, 'Line exceeds 80 characters')
  - (635, 'Line exceeds 80 characters')
  - (636, 'Line exceeds 80 characters')
  - (640, 'Line exceeds 80 characters')
  - (647, 'Line exceeds 80 characters')
  - (648, 'Line exceeds 80 characters')
  - (654, 'Line exceeds 80 characters')
  - (661, 'Line exceeds 80 characters')
  - (662, 'Line exceeds 80 characters')
  - (666, 'Line exceeds 80 characters')
  - (668, 'Line exceeds 80 characters')
  - (673, 'Line exceeds 80 characters')
  - (678, 'Line exceeds 80 characters')
  - (685, 'Line exceeds 80 characters')
  - (690, 'Line exceeds 80 characters')
  - (697, 'Line exceeds 80 characters')
  - (698, 'Line exceeds 80 characters')
  - (704, 'Line exceeds 80 characters')
  - (711, 'Line exceeds 80 characters')
  - (712, 'Line exceeds 80 characters')
  - (716, 'Line exceeds 80 characters')
  - (718, 'Line exceeds 80 characters')

**Comment by lind0118** [comment]
I got it.
