### ISSUE TITLE
Issue-implement exhchange  bid & ask price comparison

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/bestside-exchange#33]
Automated Review Comments
Issues in app/services/compare_exchange.py:
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
Issues in frontend/package-lock.json:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
  - (3, 'Line exceeds 80 characters')
  - (3, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
  - (24, 'Line exceeds 80 characters')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
  - (32, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (36, 'Line exceeds 80 characters')
  - (36, 'Hardcoded string found')
  - (37, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (50, 'Line exceeds 80 characters')
  - (50, 'Hardcoded string found')
  - (51, 'Line exceeds 80 characters')
  - (51, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (62, 'Line exceeds 80 characters')
  - (62, 'Hardcoded string found')
  - (63, 'Line exceeds 80 characters')
  - (63, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (74, 'Line exceeds 80 characters')
  - (74, 'Hardcoded string found')
  - (75, 'Line exceeds 80 characters')
  - (75, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (79, 'Line exceeds 80 characters')
  - (79, 'Hardcoded string found')
  - (80, 'Line exceeds 80 characters')
  - (80, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (83, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (85, 'Line exceeds 80 characters')
  - (85, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (91, 'Line exceeds 80 characters')
  - (91, 'Hardcoded string found')
  - (92, 'Line exceeds 80 characters')
  - (92, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
  - (102, 'Hardcoded string found')
  - (103, 'Line exceeds 80 characters')
  - (103, 'Hardcoded string found')
  - (104, 'Line exceeds 80 characters')
  - (104, 'Hardcoded string found')
  - (107, 'Hardcoded string found')
  - (108, 'Line exceeds 80 characters')
  - (108, 'Hardcoded string found')
  - (109, 'Line exceeds 80 characters')
  - (109, 'Hardcoded string found')
  - (112, 'Hardcoded string found')
  - (113, 'Line exceeds 80 characters')
  - (113, 'Hardcoded string found')
  - (114, 'Line exceeds 80 characters')
  - (114, 'Hardcoded string found')
  - (117, 'Hardcoded string found')
  - (118, 'Line exceeds 80 characters')
  - (118, 'Hardcoded string found')
  - (119, 'Line exceeds 80 characters')
  - (119, 'Hardcoded string found')
  - (122, 'Hardcoded string found')
  - (123, 'Line exceeds 80 characters')
  - (123, 'Hardcoded string found')
  - (124, 'Line exceeds 80 characters')
  - (124, 'Hardcoded string found')
  - (127, 'Hardcoded string found')
  - (128, 'Line exceeds 80 characters')
  - (128, 'Hardcoded string found')
  - (134, 'Hardcoded string found')
  - (135, 'Line exceeds 80 characters')
  - (135, 'Hardcoded string found')
  - (136, 'Line exceeds 80 characters')
  - (136, 'Hardcoded string found')
  - (137, 'Hardcoded string found')
  - (149, 'Hardcoded string found')
  - (151, 'Hardcoded string found')
  - (152, 'Line exceeds 80 characters')
  - (152, 'Hardcoded string found')
  - (153, 'Hardcoded string found')
  - (158, 'Hardcoded string found')
  - (159, 'Line exceeds 80 characters')
  - (159, 'Hardcoded string found')
  - (165, 'Hardcoded string found')
  - (166, 'Line exceeds 80 characters')
  - (166, 'Hardcoded string found')
  - (167, 'Line exceeds 80 characters')
  - (167, 'Hardcoded string found')
  - (168, 'Hardcoded string found')
  - (172, 'Hardcoded string found')
  - (176, 'Hardcoded string found')
  - (177, 'Line exceeds 80 characters')
  - (177, 'Hardcoded string found')
  - (178, 'Hardcoded string found')
  - (181, 'Hardcoded string found')
  - (182, 'Line exceeds 80 characters')
  - (182, 'Hardcoded string found')
  - (184, 'Line exceeds 80 characters')
  - (184, 'Hardcoded string found')
  - (185, 'Hardcoded string found')
  - (187, 'Hardcoded string found')
  - (188, 'Hardcoded string found')
  - (189, 'Hardcoded string found')
  - (190, 'Hardcoded string found')
  - (193, 'Hardcoded string found')
  - (194, 'Line exceeds 80 characters')
  - (194, 'Hardcoded string found')
  - (200, 'Hardcoded string found')
  - (201, 'Line exceeds 80 characters')
  - (201, 'Hardcoded string found')
  - (202, 'Line exceeds 80 characters')
  - (202, 'Hardcoded string found')
  - (203, 'Hardcoded string found')
  - (211, 'Hardcoded string found')
  - (212, 'Line exceeds 80 characters')
  - (212, 'Hardcoded string found')
  - (214, 'Hardcoded string found')
  - (218, 'Hardcoded string found')
  - (219, 'Line exceeds 80 characters')
  - (219, 'Hardcoded string found')
  - (220, 'Hardcoded string found')
  - (223, 'Hardcoded string found')
  - (224, 'Line exceeds 80 characters')
  - (224, 'Hardcoded string found')
  - (226, 'Line exceeds 80 characters')
  - (226, 'Hardcoded string found')
  - (227, 'Line exceeds 80 characters')
  - (227, 'Hardcoded string found')
  - (230, 'Hardcoded string found')
  - (231, 'Line exceeds 80 characters')
  - (231, 'Hardcoded string found')
  - (232, 'Line exceeds 80 characters')
  - (232, 'Hardcoded string found')
  - (233, 'Hardcoded string found')
  - (234, 'Hardcoded string found')
  - (240, 'Hardcoded string found')
  - (241, 'Line exceeds 80 characters')
  - (241, 'Hardcoded string found')
  - (246, 'Hardcoded string found')
  - (247, 'Hardcoded string found')
  - (248, 'Hardcoded string found')
  - (249, 'Line exceeds 80 characters')
  - (249, 'Hardcoded string found')
  - (251, 'Hardcoded string found')
  - (252, 'Hardcoded string found')
  - (253, 'Hardcoded string found')
  - (255, 'Hardcoded string found')
  - (259, 'Hardcoded string found')
  - (260, 'Line exceeds 80 characters')
  - (260, 'Hardcoded string found')
  - (261, 'Line exceeds 80 characters')
  - (261, 'Hardcoded string found')
  - (262, 'Hardcoded string found')
  - (267, 'Hardcoded string found')
  - (268, 'Line exceeds 80 characters')
  - (268, 'Hardcoded string found')
  - (270, 'Line exceeds 80 characters')
  - (270, 'Hardcoded string found')
  - (271, 'Line exceeds 80 characters')
  - (271, 'Hardcoded string found')
  - (273, 'Hardcoded string found')
  - (274, 'Hardcoded string found')
  - (275, 'Hardcoded string found')
  - (276, 'Line exceeds 80 characters')
  - (276, 'Hardcoded string found')
  - (277, 'Hardcoded string found')
  - (282, 'Hardcoded string found')
  - (283, 'Hardcoded string found')
  - (284, 'Hardcoded string found')
  - (290, 'Hardcoded string found')
  - (291, 'Hardcoded string found')
  - (292, 'Line exceeds 80 characters')
  - (292, 'Hardcoded string found')
  - (295, 'Hardcoded string found')
  - (296, 'Hardcoded string found')
  - (302, 'Hardcoded string found')
  - (303, 'Line exceeds 80 characters')
  - (303, 'Hardcoded string found')
  - (304, 'Line exceeds 80 characters')
  - (304, 'Hardcoded string found')
  - (305, 'Hardcoded string found')
  - (308, 'Hardcoded string found')
  - (310, 'Hardcoded string found')
  - (311, 'Line exceeds 80 characters')
  - (311, 'Hardcoded string found')
  - (312, 'Line exceeds 80 characters')
  - (312, 'Hardcoded string found')
  - (316, 'Hardcoded string found')
  - (317, 'Hardcoded string found')
  - (318, 'Hardcoded string found')
  - (320, 'Hardcoded string found')
  - (321, 'Line exceeds 80 characters')
  - (321, 'Hardcoded string found')
  - (324, 'Hardcoded string found')
  - (325, 'Line exceeds 80 characters')
  - (325, 'Hardcoded string found')
  - (326, 'Line exceeds 80 characters')
  - (326, 'Hardcoded string found')
  - (329, 'Hardcoded string found')
  - (330, 'Line exceeds 80 characters')
  - (330, 'Hardcoded string found')
  - (331, 'Line exceeds 80 characters')
  - (331, 'Hardcoded string found')
  - (332, 'Hardcoded string found')
  - (333, 'Hardcoded string found')
  - (339, 'Hardcoded string found')
  - (340, 'Line exceeds 80 characters')
  - (340, 'Hardcoded string found')
  - (346, 'Hardcoded string found')
  - (347, 'Line exceeds 80 characters')
  - (347, 'Hardcoded string found')
  - (348, 'Line exceeds 80 characters')
  - (348, 'Hardcoded string found')
  - (349, 'Hardcoded string found')
  - (354, 'Hardcoded string found')
  - (355, 'Line exceeds 80 characters')
  - (355, 'Hardcoded string found')
  - (356, 'Line exceeds 80 characters')
  - (356, 'Hardcoded string found')
  - (357, 'Hardcoded string found')
  - (365, 'Hardcoded string found')
  - (366, 'Line exceeds 80 characters')
  - (366, 'Hardcoded string found')
  - (372, 'Hardcoded string found')
  - (373, 'Line exceeds 80 characters')
  - (373, 'Hardcoded string found')
  - (374, 'Line exceeds 80 characters')
  - (374, 'Hardcoded string found')
  - (375, 'Hardcoded string found')
  - (384, 'Hardcoded string found')
  - (387, 'Hardcoded string found')
  - (389, 'Hardcoded string found')
  - (390, 'Line exceeds 80 characters')
  - (390, 'Hardcoded string found')
  - (391, 'Line exceeds 80 characters')
  - (391, 'Hardcoded string found')
  - (392, 'Hardcoded string found')
  - (398, 'Hardcoded string found')
  - (399, 'Hardcoded string found')
  - (400, 'Line exceeds 80 characters')
  - (400, 'Hardcoded string found')
  - (405, 'Hardcoded string found')
  - (406, 'Hardcoded string found')
  - (407, 'Hardcoded string found')
  - (408, 'Line exceeds 80 characters')
  - (408, 'Hardcoded string found')
  - (411, 'Hardcoded string found')
  - (412, 'Line exceeds 80 characters')
  - (412, 'Hardcoded string found')
Issues in frontend/package.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
Issues in frontend/src/App.js:
  - (4, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (18, 'Line exceeds 80 characters')
  - (25, 'Hardcoded string found')
  - (39, 'Line exceeds 80 characters')
  - (60, 'Hardcoded string found')
  - (77, 'Line exceeds 80 characters')
  - (79, 'Line exceeds 80 characters')
  - (88, 'Line exceeds 80 characters')
  - (90, 'Line exceeds 80 characters')
  - (101, 'Line exceeds 80 characters')
  - (102, 'Line exceeds 80 characters')
  - (102, 'Hardcoded string found')
  - (104, 'Line exceeds 80 characters')
  - (110, 'Line exceeds 80 characters')
  - (111, 'Line exceeds 80 characters')
  - (111, 'Hardcoded string found')
  - (113, 'Line exceeds 80 characters')
  - (122, 'Line exceeds 80 characters')
  - (126, 'Hardcoded string found')
  - (127, 'Line exceeds 80 characters')
  - (127, 'Hardcoded string found')
  - (128, 'Line exceeds 80 characters')
  - (130, 'Line exceeds 80 characters')
  - (130, 'Hardcoded string found')
  - (131, 'Line exceeds 80 characters')
  - (165, 'Hardcoded string found')
  - (166, 'Line exceeds 80 characters')
  - (166, 'Hardcoded string found')
  - (167, 'Line exceeds 80 characters')
  - (169, 'Line exceeds 80 characters')
  - (171, 'Line exceeds 80 characters')
  - (171, 'Hardcoded string found')
  - (172, 'Line exceeds 80 characters')
  - (174, 'Line exceeds 80 characters')
  - (183, 'Line exceeds 80 characters')
  - (199, 'Line exceeds 80 characters')
  - (200, 'Line exceeds 80 characters')
  - (204, 'Line exceeds 80 characters')
  - (215, 'Line exceeds 80 characters')
  - (229, 'Line exceeds 80 characters')
  - (230, 'Line exceeds 80 characters')
  - (234, 'Line exceeds 80 characters')
  - (251, 'Line exceeds 80 characters')
  - (252, 'Line exceeds 80 characters')
  - (262, 'Line exceeds 80 characters')
  - (263, 'Line exceeds 80 characters')
  - (268, 'Hardcoded string found')
  - (269, 'Line exceeds 80 characters')
  - (274, 'Hardcoded string found')
  - (275, 'Line exceeds 80 characters')
  - (276, 'Line exceeds 80 characters')
  - (281, 'Hardcoded string found')
  - (282, 'Line exceeds 80 characters')
  - (287, 'Hardcoded string found')
  - (288, 'Line exceeds 80 characters')
  - (293, 'Hardcoded string found')
  - (294, 'Line exceeds 80 characters')
  - (299, 'Hardcoded string found')
  - (300, 'Line exceeds 80 characters')
  - (304, 'Hardcoded string found')
  - (322, 'Hardcoded string found')
  - (323, 'Line exceeds 80 characters')
  - (328, 'Hardcoded string found')
  - (329, 'Line exceeds 80 characters')
  - (334, 'Hardcoded string found')
  - (335, 'Line exceeds 80 characters')
  - (339, 'Hardcoded string found')
  - (348, 'Line exceeds 80 characters')
  - (351, 'Line exceeds 80 characters')
  - (357, 'Line exceeds 80 characters')
  - (365, 'Line exceeds 80 characters')
  - (371, 'Line exceeds 80 characters')
  - (373, 'Line exceeds 80 characters')
  - (374, 'Line exceeds 80 characters')
  - (379, 'Line exceeds 80 characters')
  - (380, 'Line exceeds 80 characters')
  - (390, 'Line exceeds 80 characters')
  - (393, 'Line exceeds 80 characters')
  - (395, 'Line exceeds 80 characters')
  - (396, 'Line exceeds 80 characters')
  - (398, 'Line exceeds 80 characters')
  - (399, 'Line exceeds 80 characters')
  - (409, 'Line exceeds 80 characters')
  - (412, 'Line exceeds 80 characters')
  - (414, 'Line exceeds 80 characters')
  - (415, 'Line exceeds 80 characters')
  - (417, 'Line exceeds 80 characters')
  - (418, 'Line exceeds 80 characters')

**Comment by lind0118** [comment]
I got it.
