### ISSUE TITLE
Issue-add exchanges and API

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/bestside-exchange#4]
Automated Review Comments
Issues in Dockerfile:
  - (11, 'Hardcoded string found')
Issues in README.md:
  - (3, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
Issues in app/core/config.py:
  - (20, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
Issues in app/core/exchanges/blockchain_api.py:
  - (23, 'Hardcoded string found')
Issues in app/core/exchanges/gemini.py:
  - (38, 'Hardcoded string found')
Issues in app/main.py:
  - (6, 'Line exceeds 80 characters')
Issues in docker-compose.yml:
  - (9, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Line exceeds 80 characters')
Issues in docs/bestside-exchange.drawio:
  - (2, 'Line exceeds 80 characters')
Issues in makefile:
  - (2, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (54, 'Hardcoded string found')

**Comment by lind0118** [comment]
I got it.
